In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator,SimpleImputer

In [2]:
df=pd.read_csv("train.csv",usecols=['Age','Survived','Fare'])

In [3]:
df.head()

,Survived,Age,Fare
0,0,22.0,7.2500
1,1,38.0,71.2833
2,1,26.0,7.9250
3,1,35.0,53.1000
4,0,35.0,8.0500


In [4]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [5]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [7]:
X_train.head()

,Age,Fare
331,45.5,28.5000
733,23.0,13.0000
382,32.0,7.9250
704,26.0,7.8542
813,6.0,31.2750


In [8]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64

In [9]:
si=SimpleImputer()

X_train_mean=si.fit_transform(X_train)
X_test_mean=si.transform(X_test)

In [28]:
X_test_mean[0]

array([29.49884615, 15.2458    ])

In [11]:
from sklearn.linear_model import LogisticRegression


In [12]:
clf=LogisticRegression()

clf.fit(X_train_mean,y_train)
y_pred=clf.predict(X_test_mean)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6480446927374302

In [13]:
mi=MissingIndicator()
mi.fit(X_train)

MissingIndicator()

In [14]:
mi.features_

array([0])

In [15]:
X_train_missing=mi.transform(X_train)
X_test_missing=mi.transform(X_test)

In [16]:
X_train_missing[0]

array([False])

In [17]:
X_train['Age_NA']=X_train_missing

In [18]:
X_test['Age_NA']=X_test_missing

In [19]:
X_train.head()

,Age,Fare,Age_NA
331,45.5,28.5000,False
733,23.0,13.0000,False
382,32.0,7.9250,False
704,26.0,7.8542,False
813,6.0,31.2750,False


In [20]:
X_test.head()

,Age,Fare,Age_NA
709,NaN,15.2458,True
439,31.0,10.5000,False
840,20.0,7.9250,False
720,6.0,33.0000,False
39,14.0,11.2417,False


In [21]:
si=SimpleImputer()

X_train_trf=si.fit_transform(X_train)
X_test_trf=si.transform(X_test)

In [22]:
X_train_trf

array([[ 45.5   ,  28.5   ,   0.    ],
       [ 23.    ,  13.    ,   0.    ],
       [ 32.    ,   7.925 ,   0.    ],
       ...,
       [ 41.    ,  14.1083,   0.    ],
       [ 14.    , 120.    ,   0.    ],
       [ 21.    ,  77.2875,   0.    ]])

In [23]:
clf=LogisticRegression()

clf.fit(X_train_trf,y_train)
y_pred=clf.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.6368715083798883

In [27]:
si=SimpleImputer(add_indicator=True)   # by using add_indicator we do not need to use MissingIndicator class

In [25]:
X_train=si.fit_transform(X_train)
X_test=si.transform(X_test)

In [26]:
 X_train

array([[ 45.5   ,  28.5   ,   0.    ,   0.    ],
       [ 23.    ,  13.    ,   0.    ,   0.    ],
       [ 32.    ,   7.925 ,   0.    ,   0.    ],
       ...,
       [ 41.    ,  14.1083,   0.    ,   0.    ],
       [ 14.    , 120.    ,   0.    ,   0.    ],
       [ 21.    ,  77.2875,   0.    ,   0.    ]])